// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v4.25.1
// source: proto/gordian/rpc/core/v1/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResultTx) Reset() {
	*x = ResultTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gordian_rpc_core_v1_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultTx) ProtoMessage() {}

func (x *ResultTx) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gordian_rpc_core_v1_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultTx.ProtoReflect.Descriptor instead.
func (*ResultTx) Descriptor() ([]byte, []int) {
	return file_proto_gordian_rpc_core_v1_types_proto_rawDescGZIP(), []int{0}
}

type ResultBroadcastTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResultBroadcastTx) Reset() {
	*x = ResultBroadcastTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gordian_rpc_core_v1_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultBroadcastTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultBroadcastTx) ProtoMessage() {}

func (x *ResultBroadcastTx) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gordian_rpc_core_v1_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultBroadcastTx.ProtoReflect.Descriptor instead.
func (*ResultBroadcastTx) Descriptor() ([]byte, []int) {
	return file_proto_gordian_rpc_core_v1_types_proto_rawDescGZIP(), []int{1}
}

type ResultBlockSearch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResultBlockSearch) Reset() {
	*x = ResultBlockSearch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gordian_rpc_core_v1_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultBlockSearch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultBlockSearch) ProtoMessage() {}

func (x *ResultBlockSearch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gordian_rpc_core_v1_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultBlockSearch.ProtoReflect.Descriptor instead.
func (*ResultBlockSearch) Descriptor() ([]byte, []int) {
	return file_proto_gordian_rpc_core_v1_types_proto_rawDescGZIP(), []int{2}
}

type ResultCommit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResultCommit) Reset() {
	*x = ResultCommit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gordian_rpc_core_v1_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultCommit) ProtoMessage() {}

func (x *ResultCommit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gordian_rpc_core_v1_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultCommit.ProtoReflect.Descriptor instead.
func (*ResultCommit) Descriptor() ([]byte, []int) {
	return file_proto_gordian_rpc_core_v1_types_proto_rawDescGZIP(), []int{3}
}

type ResultABCIQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResultABCIQuery) Reset() {
	*x = ResultABCIQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gordian_rpc_core_v1_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultABCIQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultABCIQuery) ProtoMessage() {}

func (x *ResultABCIQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gordian_rpc_core_v1_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultABCIQuery.ProtoReflect.Descriptor instead.
func (*ResultABCIQuery) Descriptor() ([]byte, []int) {
	return file_proto_gordian_rpc_core_v1_types_proto_rawDescGZIP(), []int{4}
}

var File_proto_gordian_rpc_core_v1_types_proto protoreflect.FileDescriptor

var file_proto_gordian_rpc_core_v1_types_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x2f,
	0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x67, 0x6f, 0x72, 0x64, 0x69, 0x61, 0x6e,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x0a, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x54, 0x78, 0x22, 0x13, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54, 0x78, 0x22, 0x13, 0x0a,
	0x11, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x41, 0x42, 0x43, 0x49,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x62, 0x66, 0x74, 0x2f, 0x63, 0x6f, 0x6d,
	0x65, 0x74, 0x62, 0x66, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gordian_rpc_core_v1_types_proto_rawDescOnce sync.Once
	file_proto_gordian_rpc_core_v1_types_proto_rawDescData = file_proto_gordian_rpc_core_v1_types_proto_rawDesc
)

func file_proto_gordian_rpc_core_v1_types_proto_rawDescGZIP() []byte {
	file_proto_gordian_rpc_core_v1_types_proto_rawDescOnce.Do(func() {
		file_proto_gordian_rpc_core_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gordian_rpc_core_v1_types_proto_rawDescData)
	})
	return file_proto_gordian_rpc_core_v1_types_proto_rawDescData
}

var file_proto_gordian_rpc_core_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_gordian_rpc_core_v1_types_proto_goTypes = []interface{}{
	(*ResultTx)(nil),          // 0: gordian.rpc.core.v1.ResultTx
	(*ResultBroadcastTx)(nil), // 1: gordian.rpc.core.v1.ResultBroadcastTx
	(*ResultBlockSearch)(nil), // 2: gordian.rpc.core.v1.ResultBlockSearch
	(*ResultCommit)(nil),      // 3: gordian.rpc.core.v1.ResultCommit
	(*ResultABCIQuery)(nil),   // 4: gordian.rpc.core.v1.ResultABCIQuery
}
var file_proto_gordian_rpc_core_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gordian_rpc_core_v1_types_proto_init() }
func file_proto_gordian_rpc_core_v1_types_proto_init() {
	if File_proto_gordian_rpc_core_v1_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gordian_rpc_core_v1_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gordian_rpc_core_v1_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultBroadcastTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gordian_rpc_core_v1_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultBlockSearch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gordian_rpc_core_v1_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultCommit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gordian_rpc_core_v1_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultABCIQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gordian_rpc_core_v1_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gordian_rpc_core_v1_types_proto_goTypes,
		DependencyIndexes: file_proto_gordian_rpc_core_v1_types_proto_depIdxs,
		MessageInfos:      file_proto_gordian_rpc_core_v1_types_proto_msgTypes,
	}.Build()
	File_proto_gordian_rpc_core_v1_types_proto = out.File
	file_proto_gordian_rpc_core_v1_types_proto_rawDesc = nil
	file_proto_gordian_rpc_core_v1_types_proto_goTypes = nil
	file_proto_gordian_rpc_core_v1_types_proto_depIdxs = nil
}
