// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: proto/server/grpc.proto

package ggrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GordianGRPC_GetBlocksWatermark_FullMethodName = "/server.GordianGRPC/GetBlocksWatermark"
	GordianGRPC_GetValidators_FullMethodName      = "/server.GordianGRPC/GetValidators"
)

// GordianGRPCClient is the client API for GordianGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GordianGRPCClient interface {
	GetBlocksWatermark(ctx context.Context, in *CurrentBlockRequest, opts ...grpc.CallOption) (*CurrentBlockResponse, error)
	GetValidators(ctx context.Context, in *GetValidatorsRequest, opts ...grpc.CallOption) (*GetValidatorsResponse, error)
}

type gordianGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewGordianGRPCClient(cc grpc.ClientConnInterface) GordianGRPCClient {
	return &gordianGRPCClient{cc}
}

func (c *gordianGRPCClient) GetBlocksWatermark(ctx context.Context, in *CurrentBlockRequest, opts ...grpc.CallOption) (*CurrentBlockResponse, error) {
	out := new(CurrentBlockResponse)
	err := c.cc.Invoke(ctx, GordianGRPC_GetBlocksWatermark_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gordianGRPCClient) GetValidators(ctx context.Context, in *GetValidatorsRequest, opts ...grpc.CallOption) (*GetValidatorsResponse, error) {
	out := new(GetValidatorsResponse)
	err := c.cc.Invoke(ctx, GordianGRPC_GetValidators_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GordianGRPCServer is the server API for GordianGRPC service.
// All implementations must embed UnimplementedGordianGRPCServer
// for forward compatibility
type GordianGRPCServer interface {
	GetBlocksWatermark(context.Context, *CurrentBlockRequest) (*CurrentBlockResponse, error)
	GetValidators(context.Context, *GetValidatorsRequest) (*GetValidatorsResponse, error)
	mustEmbedUnimplementedGordianGRPCServer()
}

// UnimplementedGordianGRPCServer must be embedded to have forward compatible implementations.
type UnimplementedGordianGRPCServer struct {
}

func (UnimplementedGordianGRPCServer) GetBlocksWatermark(context.Context, *CurrentBlockRequest) (*CurrentBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlocksWatermark not implemented")
}
func (UnimplementedGordianGRPCServer) GetValidators(context.Context, *GetValidatorsRequest) (*GetValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidators not implemented")
}
func (UnimplementedGordianGRPCServer) mustEmbedUnimplementedGordianGRPCServer() {}

// UnsafeGordianGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GordianGRPCServer will
// result in compilation errors.
type UnsafeGordianGRPCServer interface {
	mustEmbedUnimplementedGordianGRPCServer()
}

func RegisterGordianGRPCServer(s grpc.ServiceRegistrar, srv GordianGRPCServer) {
	s.RegisterService(&GordianGRPC_ServiceDesc, srv)
}

func _GordianGRPC_GetBlocksWatermark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GordianGRPCServer).GetBlocksWatermark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GordianGRPC_GetBlocksWatermark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GordianGRPCServer).GetBlocksWatermark(ctx, req.(*CurrentBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GordianGRPC_GetValidators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GordianGRPCServer).GetValidators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GordianGRPC_GetValidators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GordianGRPCServer).GetValidators(ctx, req.(*GetValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GordianGRPC_ServiceDesc is the grpc.ServiceDesc for GordianGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GordianGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.GordianGRPC",
	HandlerType: (*GordianGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlocksWatermark",
			Handler:    _GordianGRPC_GetBlocksWatermark_Handler,
		},
		{
			MethodName: "GetValidators",
			Handler:    _GordianGRPC_GetValidators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/server/grpc.proto",
}
