// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.11.2
// source: shred.proto

package shredding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShredMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Total     uint32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	BlockHash []byte `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Height    uint64 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Type      int32  `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	GroupId   []byte `protobuf:"bytes,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *ShredMessage) Reset() {
	*x = ShredMessage{}
	mi := &file_shred_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShredMessage) ProtoMessage() {}

func (x *ShredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shred_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShredMessage.ProtoReflect.Descriptor instead.
func (*ShredMessage) Descriptor() ([]byte, []int) {
	return file_shred_proto_rawDescGZIP(), []int{0}
}

func (x *ShredMessage) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ShredMessage) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ShredMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ShredMessage) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ShredMessage) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ShredMessage) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ShredMessage) GetGroupId() []byte {
	if x != nil {
		return x.GroupId
	}
	return nil
}

var File_shred_proto protoreflect.FileDescriptor

var file_shred_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x68, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x67,
	0x74, 0x75, 0x72, 0x62, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x68, 0x72, 0x65, 0x64, 0x64, 0x69, 0x6e,
	0x67, 0x22, 0xb4, 0x01, 0x0a, 0x0c, 0x53, 0x68, 0x72, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x2d, 0x65,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x67, 0x6f, 0x72, 0x64, 0x69, 0x61, 0x6e, 0x2f, 0x67, 0x74,
	0x75, 0x72, 0x62, 0x69, 0x6e, 0x65, 0x2f, 0x73, 0x68, 0x72, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shred_proto_rawDescOnce sync.Once
	file_shred_proto_rawDescData = file_shred_proto_rawDesc
)

func file_shred_proto_rawDescGZIP() []byte {
	file_shred_proto_rawDescOnce.Do(func() {
		file_shred_proto_rawDescData = protoimpl.X.CompressGZIP(file_shred_proto_rawDescData)
	})
	return file_shred_proto_rawDescData
}

var file_shred_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shred_proto_goTypes = []any{
	(*ShredMessage)(nil), // 0: gturbine.shredding.ShredMessage
}
var file_shred_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shred_proto_init() }
func file_shred_proto_init() {
	if File_shred_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shred_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shred_proto_goTypes,
		DependencyIndexes: file_shred_proto_depIdxs,
		MessageInfos:      file_shred_proto_msgTypes,
	}.Build()
	File_shred_proto = out.File
	file_shred_proto_rawDesc = nil
	file_shred_proto_goTypes = nil
	file_shred_proto_depIdxs = nil
}
