name: gcosmos build and verify

on:
  pull_request:
  push:
    tags:
    - '**'
    branches:
    - '**'

env:
  GORDIAN_TEST_TIME_FACTOR: 4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod # Use whatever version is in the header of go.mod.

    - name: Setup Git User
      run: |
        git config --global user.name "abc"
        git config --global user.email "abc@example.com"

    - name: Clone Cosmos-SDK with patches
      working-directory: gcosmos
      run: |
        bash _cosmosvendor/sync_sdk.bash
        go build -o gcosmos .

    - name: Build, setup, and start background gcosmos
      working-directory: gcosmos
      run: |
        ./scripts/run_gcosmos.sh &

    - name: Verify gcosmos is running
      run: |
        sleep 5
        RESP=$(curl -s http://127.0.0.1:26657/blocks/watermark --max-time 5 | jq .VotingHeight)
        if [[ "$RESP" -le 1 ]]; then
          echo "Failed to start gcosmos"
          exit 1
        fi
        echo "gcosmos is running"

    - name: Cleanup
      run:
        killall -9 gcosmos
